### ISSUE TITLE
Include a default config overlay for docker-best-practice values

### ISSUE THREAD

**Issue by ebullient** [WASdev/ci.docker#105]
a) turn off file polling (switch to mbean)
b) set coreThreads to a reasonable value (5) so the executor service isn't going off of potentially bad virtualized values.
c) turn off deferred application start

Something like the following in configDropins/defaults:

```
    <!-- turn off polling -->
    <config updateTrigger="mbean" />
    <applicationMonitor dropinsEnabled="false" updateTrigger="mbean"/>

    <!-- This is required to prevent the web apps from being lazily loaded -->
    <webContainer deferServletLoad="false"/>
    <!-- The JVM can get confused about available CPU in virtualized envs -->
    <executor coreThreads="5"/>
```

**Comment by arthurdm** [comment]
Some of our docs from Docker Hub demonstrate using the `dropins` folder, so it would be weird if that didn't work without an additional server.xml to override that default.  

I realize that this issue was opened over a year ago, so since then there has been work in Liberty 18001 for optimizing the executor cores in cloud environments.  

Do you still feels there's particular config for a docker container environment that wouldn't also be a best practice for outside a docker environment?

**Comment by gjdeval** [comment]
Changes made in Liberty 18001 to the Liberty DefaultExecutor initialization default behavior (when coreThreads is not set) take account of Docker container cpu allocation, in addition to other factors. So afaik Liberty default threadpool sizing should work 'properly' in Docker from 18001 on, i.e. it will start the pool at twice the number of 'virtual cpus' configured in Docker, analogous to the starting point of twice the number of hardware threads in non-Docker environments.
If/when we discover Docker configs that don't seem to be starting the threadpool by default at a reasonable size, I'd love to know the particulars so we can adapt to properly handle that situation as well.

**Comment by arthurdm** [comment]
Thanks for the info @gjdeval 

Closing this issue, given the reasons from the last 2 comments.
