### ISSUE TITLE
Two repos - what's the diff?

### ISSUE THREAD

**Issue by davidkarlsen** [WASdev/ci.docker#310]
What's the difference between:
https://hub.docker.com/r/ibmcom/websphere-liberty
https://hub.docker.com/_/websphere-liberty

both seem pretty IBM official? Will one of them die in favour of the other?

**Comment by arthurdm** [comment]
hi @davidkarlsen - these are explained [here](https://github.com/WASdev/ci.docker#docker-hub-images), but basically:  the `ibmcom` is the repository for UBI-based images, and the second one is for Ubuntu-based images.  

We had to split the repos because UBI wasn't contributed into Docker Hub's "official image program" - but it is an official image that comes straight from the Red Hat registry.

**Comment by davidkarlsen** [comment]
Will both continue to be developed? What is the reason the UBI ones are recommended?

**Comment by arthurdm** [comment]
Both will continue for now.  We view UBI as a more robust / enterprise-ready OS.

**Comment by davidkarlsen** [comment]
Thank you for your information!
