### ISSUE TITLE
Unable to download a version 20.0.07 .

### ISSUE THREAD

**Issue by Vkad00** [WASdev/ci.docker#350]
We are unable to download just by mentioning version number. We get the below error. 
manifest for websphere-liberty:20.0.0.7 not found

Is it a new requriement to append the image version as 20.0.0.7-kernel-java8-ibmjava ?

**Comment by arthurdm** [comment]
hi @Vkad00 - we actually never had a way to just specify the version in the tag.  It always needs to be augmented with a suffix that defines the exact tag.  The current tags are documented here for Ubuntu https://hub.docker.com/_/websphere-liberty, and here for UBI https://hub.docker.com/r/ibmcom/websphere-liberty/

**Comment by Vkad00** [comment]
It was available earlier to download just the kernel by putting my version number like 19.0.0.4 etc. It has changed from V20 onwards.

**Comment by arthurdm** [comment]
as I recall, even back then you still needed to specify an additional tag, like `19.0.0.2-webProfile8` for example.  All of the old tags are still available in the tags tab, e.g. https://hub.docker.com/_/websphere-liberty/?tab=tags&page=1&name=19.0.0.2

But anyhow, the pattern for the supported images is the version (20.0.0.7) + the specific tag.  In terms of tags we have since simplified to just have `kernel` and `full` variations.  

If any more clarification is needed let us know.
