### ISSUE TITLE
Java17 flavour

### ISSUE THREAD

**Issue by davidkarlsen** [WASdev/ci.docker#415]
It seems java17 is supported from 21.0.10.0 https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-updating-jre-java-sdk - but there is no 17 flavour in this repo?

**Comment by leochr** [comment]
Update: we are working on adding the Ubuntu based Liberty images with Java 17. Expect them to be available in Docker Hub by the end of next week. We are blocked on the UBI images due to an issue with Java images. Once that's resolved, we'll proceed with adding UBI based Liberty images for Java 17.  Similar issue for Open Liberty has [issue](https://github.com/OpenLiberty/ci.docker/issues/277) additional information.

**Comment by leochr** [comment]
Java 17 images are added. Closing.
