### ISSUE TITLE
image tags should be immutable / provide tags for the latest version

### ISSUE THREAD

**Issue by tobilarscheid** [WASdev/ci.docker#90]
Hi,

our team is currently unsatisfied with how the wlp images are tagged in docker-hub. For the latest version (should be 16.0.0.2 at the time of writing) you do not provide a specific tag. Instead, this version is only accessible through the latest / javaee7 /webProfile7 ... tags. This leads to serious problems, as there is no way to explicitly depend on 16.0.0.2 or one of it's subsets. Also, depending on for example webProfile7 tag is not satisfying as at some point in the future this tag will point to a more recent release - which can lead to pretty unobvious problems, when one machine still has an older cached version and another doesn't. (docker does only reevaluate the latest tag on every build, other tags are served from the cache indefinitely, see this discussion for details: https://github.com/docker/docker/issues/13331)

We propose to provide explicit tags for even the latest version and to point out that for example the webProfile7 tag does not mean latest webProfile7 but instead means whatever version of webProfile7 docker has cached for you.

Regards,

Tobi

**Comment by davidcurrie** [comment]
Hi Tobi

Apologies for the delay in responding, you hit the start of my vacation. Thanks for raising this issue and I'd like to explore the problem that you see here.

Firstly, as I read the issue that you reference it is stating that the problem is really with `docker run` as `docker build` provides the `--pull` option which will always attempt to get the latest image for a given name/tag to build from. If we were to tag images with a specific Liberty version, they would still not be immutable as they would get rebuilt when the base Ubuntu image gets updated. If you really do want to prereq a specific image then you should use the digest when you refer to it. Lastly, there is nothing to prevent you from storing images in your own registry and adding additional tags.

Regards
David

**Comment by tobilarscheid** [comment]
Hi david,

thanks for your reply, I hope you enjoyed your vacation. I didn't know the --pull option for build, this partly solves the problem.

One of my points still remains, though: There is no explicit tag for the WLP 16.0... versions. If I now used :latest with --pull I would suddenly get the next version when it's available.

If you added these, I would be totally fine - with --pull I could use the really latest version whenever I want to and with explicit tags for version 16 I could use these in a reliable fashion - that they are not strictly immutable because of changes in the ubuntu image is acceptable in my opinion, as I assume the ubuntu updates will not introduce breaking changes to the WLP.

Regards,

Tobi

**Comment by davidcurrie** [comment]
Our zero migration policy should mean that you don't experience issues moving from one Liberty fix pack to the next providing your configuration remains unchanged and we would recommend that customers always try to remain current.

As you observe, we did create version tags for the 8.5.5 images but the images were only being rebuilt whilst they were the latest leading to older images getting steadily more back-level in terms of Ubuntu vulnerabilities. Without the ability to remove these older images we are reluctant to perpetuate this situation with the 16.0.0 releases.

Lastly, these images contain a developer licensed Liberty and only making the latest version available is consistent with our download policy on wasdev.net. For production images (which you would need to build locally) then I appreciate that you may wish to use a different policy.
